create table imported_repository (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    repository_url varchar(1000) not null,
    repository_name varchar(200) not null,
    local_path varchar(2000) not null,
    commit_hash varchar(64) not null,
    imported_at timestamp not null default current_timestamp
);

create index idx_imported_repository_project on imported_repository(project_id, imported_at desc);
